### ISSUE TITLE
Wording

### ISSUE THREAD

**Issue by Kewey** [Kewey/swoome_app#9]
Ecran add expense:
Sauveur -> payé par

Inscription:
Vérifier les textes

**Comment by tsiatka** [comment]
mauvais texte inscription mot de passe

peut être changer le wording lors de la connexion

au moment du choix du groupe garder le terme "foyer" ou non ?

au moment de créer un groupe, garder le terme "maison" ou non tout au long du formulaire ? + il y a écrit "tu dois créer ou rejoindre une maison" alors qu'on est déjà dans le formulaire de création 

Dépenses total du groupe -> Dépenses totales du groupe

Theme sombre/clair -> Thème

Modifier les parametres -> Modifier les paramètres

Notifications activé -> activées

A définir -> À définir

Oula -> Ouh là
